version: '3.8'
services:
  frontend:
    env_file:
      - .env
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - BACKEND_URL=${BACKEND_URL}
        - FRONTEND_PORT=${FRONTEND_PORT}
    ports:
      - ${FRONTEND_PORT}:80
    environment:
      - BACKEND_URL=${BACKEND_URL}
      - FRONTEND_PORT=${FRONTEND_PORT}